# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Create env files
        run: |
          cat << EOF > ${{ github.workspace }}/apps/admin/.env.local
          NODE_ENV="production"
          NEXT_PUBLIC_NODE_ENV="production"
          NEXT_PUBLIC_GRAPHQL_SERVER=${{secrets.GRAPHQL_SERVER}}
          NEXT_PUBLIC_SECRET_API_KEY=${{ secrets.SECRET_MUTATION_KEY }}

          NEXT_PUBLIC_API_KEY=${{ secrets.FIREBASE_CLIENT_API_KEY }}
          NEXT_PUBLIC_AUTH_DOMAIN=${{ secrets.FIREBASE_CLIENT_AUTH_DOMAIN }}
          NEXT_PUBLIC_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_STORAGE_BUCKET=${{ secrets.FIREBASE_CLIENT_STORAGE_BUCKET }}
          NEXT_PUBLIC_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_CLIENT_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_APP_ID=${{ secrets.FIREBASE_CLIENT_APP_ID }}
          EOF

          cat << EOF > ${{ github.workspace }}/apps/server/.env
          NODE_ENV="production"
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_MUTATION_KEY=${{ secrets.SECRET_MUTATION_KEY }}
          SECRET_QUERY_KEY=${{ secrets.SECRET_QUERY_KEY }}

          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          EOF

          cat << EOF > ${{ github.workspace }}/apps/web/.env.local
          NODE_ENV="production"
          NEXT_PUBLIC_NODE_ENV="production"
          NEXT_PUBLIC_GRAPHQL_SERVER=${{secrets.GRAPHQL_SERVER}}
          SECRET_API_KEY=${{ secrets.SECRET_QUERY_KEY }}

          NEXT_PUBLIC_RECAPTCHA_KEY=${{ secrets.RECAPTCHA_SITE_KEY }}
          SECRET_RECAPTCHA_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}

          NEXT_PUBLIC_API_KEY=${{ secrets.FIREBASE_CLIENT_API_KEY }}
          NEXT_PUBLIC_AUTH_DOMAIN=${{ secrets.FIREBASE_CLIENT_AUTH_DOMAIN }}
          NEXT_PUBLIC_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_STORAGE_BUCKET=${{ secrets.FIREBASE_CLIENT_STORAGE_BUCKET }}
          NEXT_PUBLIC_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_CLIENT_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_APP_ID=${{ secrets.FIREBASE_CLIENT_APP_ID }}
          EOF

      - name: Install dependencies
        run: pnpm install

      # Not enough ram for lint + type check or deploy**
      # - name: Lint & Type Check
      #   run: pnpm lint

      - name: Build Cache - Constants
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libs/constants/dist/tsconfig.tsbuildinfo
          key: ${{ runner.os }}-constants-${{ hashFiles('./libs/constants/index.ts') }}
          restore-keys: |
            ${{ runner.os }}-constants-${{ hashFiles('./libs/constants/index.ts') }}

      - name: Build Cache - Admin
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/apps/admin/.next/cache
          key: ${{ runner.os }}-admin-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('./apps/admin/src/**/*.{ts,tsx}', './libs/shared/components/**/*.{ts,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-admin-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build Cache - Server
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/apps/server/dist/tsconfig.tsbuildinfo
          key: ${{ runner.os }}-server-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('./apps/server/src/**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-server-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build Cache - Web
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/apps/web/.next/cache
          key: ${{ runner.os }}-web-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('./apps/web/src/**/*.{ts,tsx}', './libs/shared/components/**/*.{ts,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-web-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build
        run: pnpm build

      - name: Start
        run: cd ~ && pm2 reload ecosystem.config.js
