# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Create env files
        run: |
          cat << EOF > ${{ github.workspace }}/apps/admin/.env.local
          NODE_ENV="production"
          NEXT_PUBLIC_NODE_ENV="production"
          NEXT_PUBLIC_GRAPHQL_SERVER=${{secrets.GRAPHQL_SERVER}}
          NEXT_PUBLIC_SECRET_API_KEY=${{ secrets.SECRET_MUTATION_KEY }}

          NEXT_PUBLIC_API_KEY=${{ secrets.FIREBASE_CLIENT_API_KEY }}
          NEXT_PUBLIC_AUTH_DOMAIN=${{ secrets.FIREBASE_CLIENT_AUTH_DOMAIN }}
          NEXT_PUBLIC_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_STORAGE_BUCKET=${{ secrets.FIREBASE_CLIENT_STORAGE_BUCKET }}
          NEXT_PUBLIC_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_CLIENT_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_APP_ID=${{ secrets.FIREBASE_CLIENT_APP_ID }}
          EOF

          cat << EOF > ${{ github.workspace }}/apps/api/.env
          NODE_ENV="production"
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_MUTATION_KEY=${{ secrets.SECRET_MUTATION_KEY }}
          SECRET_QUERY_KEY=${{ secrets.SECRET_QUERY_KEY }}

          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          EOF

          cat << EOF > ${{ github.workspace }}/apps/web/.env.local
          NODE_ENV="production"
          NEXT_PUBLIC_NODE_ENV="production"
          NEXT_PUBLIC_GRAPHQL_SERVER=${{secrets.GRAPHQL_SERVER}}
          SECRET_API_KEY=${{ secrets.SECRET_QUERY_KEY }}
          EOF

      - name: Install dependencies
        run: pnpm install

      - name: Use Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules/.cache/turbo
            ${{ github.workspace }}/apps/admin/.next/cache
            ${{ github.workspace }}/apps/web/.next/cache
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build
        run: pnpm build

      - name: Migrate Database
        run: pnpm db:deploy

      - name: Start
        run: pm2 reload ${{ github.workspace }}/server/pm2/ecosystem.config.js
